source 'https://rubygems.org'

# Specify your gem's dependencies in HistoryModel.gemspec
gemspec

gem 'rails', '~> 5.0.1'

# Use ElasticSearch models
gem 'elasticsearch-model', git: 'git://github.com/elasticsearch/elasticsearch-rails.git'
